---
- name: Install global Python packages into the pinned interpreter
  ansible.builtin.pip:
    name: >-
      {%- set packages = [] -%}
      {%- for pkg in python_global_packages -%}
      {%- set _ = packages.append(pkg.package + ('==' + pkg.version if pkg.version != 'latest' else '')) -%}
      {%- endfor -%}
      {{ packages }}
    executable: "{{ python_install_path }}/bin/pip{{ python_version | regex_replace('^([0-9]+\\.[0-9]+).*', '\\1') }}"
    state: present
  become: true
