---
- name: Install Python from source (Unix/Linux)
  ansible.builtin.include_tasks: noauto_install_source_Unix.yml
  when: ansible_os_family != "Windows"

- name: Install Python from source (Windows)
  ansible.builtin.include_tasks: noauto_install_source_Windows.yml
  when: ansible_os_family == "Windows"
