---
- name: Converge
  hosts: all

  vars:
    ansible_user: "root"
    python_tools:
      - package: "frida-tools"
        version: "latest"
        executables: ["frida", "frida-ps", "frida-trace"]
        tool_dependencies:
          Alpine: ["npm"]

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_os_family == 'Debian'

  roles:
    - role: pluggero.python
