---
- name: Verify
  hosts: all
  gather_facts: true

  vars_files:
    - ../../defaults/main.yml

  vars:
    ansible_user: ansible
    ansible_become_password: ansible

  tasks:
    - name: Check installed version
      ansible.builtin.include_tasks: "../../tasks/noauto_check_installed_version.yml"

    - name: Assert installed version is correct
      ansible.builtin.assert:
        that:
          - "python_installed_version == python_version"

    # User-scoped tools verification
    - name: Check user Python tool install directory exists
      ansible.builtin.stat:
        path: "{{ python_tool_install_path }}"
      register: python_user_tool_dir

    - name: Assert user Python tool directory exists
      ansible.builtin.assert:
        that:
          - python_user_tool_dir.stat.exists
          - python_user_tool_dir.stat.isdir

    - name: Check user venv directory exists (mobile-security)
      ansible.builtin.stat:
        path: "{{ python_tool_venv_dir }}/mobile-security"
      register: python_user_venv_dir

    - name: Assert user venv directory exists
      ansible.builtin.assert:
        that:
          - python_user_venv_dir.stat.exists
          - python_user_venv_dir.stat.isdir

    - name: Check PATH profile script exists
      ansible.builtin.stat:
        path: "/etc/profile.d/python_path.sh"
      register: python_path_script

    - name: Assert PATH profile script exists
      ansible.builtin.assert:
        that:
          - python_path_script.stat.exists

    - name: Check user wrapper script exists (frida)
      ansible.builtin.stat:
        path: "{{ python_tool_install_path }}/frida"
      register: python_user_frida_wrapper

    - name: Assert user frida wrapper exists and is executable
      ansible.builtin.assert:
        that:
          - python_user_frida_wrapper.stat.exists
          - python_user_frida_wrapper.stat.executable

    - name: Check user wrapper script exists (objection)
      ansible.builtin.stat:
        path: "{{ python_tool_install_path }}/objection"
      register: python_user_objection_wrapper

    - name: Assert user objection wrapper exists and is executable
      ansible.builtin.assert:
        that:
          - python_user_objection_wrapper.stat.exists
          - python_user_objection_wrapper.stat.executable

    - name: Test frida command is accessible via PATH
      ansible.builtin.shell: |
        . /etc/profile.d/python_path.sh
        which frida
      register: python_frida_which
      changed_when: false

    - name: Assert frida is found in PATH
      ansible.builtin.assert:
        that:
          - python_frida_which.stdout is match(".*/" + python_tool_install_dir + "/frida")

    # System-scoped tools verification
    - name: Check system venv directory exists (ansible-lint)
      ansible.builtin.stat:
        path: "{{ python_tool_system_venv_dir }}/ansible-lint"
      register: python_system_venv_dir

    - name: Assert system venv directory exists
      ansible.builtin.assert:
        that:
          - python_system_venv_dir.stat.exists
          - python_system_venv_dir.stat.isdir

    - name: Check system wrapper script exists (ansible-lint)
      ansible.builtin.stat:
        path: "{{ python_tool_system_bin }}/ansible-lint"
      register: python_system_ansible_lint_wrapper

    - name: Assert system ansible-lint wrapper exists and is executable
      ansible.builtin.assert:
        that:
          - python_system_ansible_lint_wrapper.stat.exists
          - python_system_ansible_lint_wrapper.stat.executable

    - name: Test ansible-lint is accessible in system PATH
      ansible.builtin.command: which ansible-lint
      register: ansible_lint_which
      changed_when: false

    - name: Assert ansible-lint is found in system PATH
      ansible.builtin.assert:
        that:
          - ansible_lint_which.stdout == python_tool_system_bin + "/ansible-lint"

    - name: Verify critical Python modules are available
      ansible.builtin.command:
        cmd: |
          python3 -c "
          import sys
          modules = ['ssl', 'sqlite3', 'zlib', 'bz2', 'lzma', 'readline', '_ctypes', '_gdbm', '_curses']
          failed = []
          for module in modules:
              try:
                  __import__(module)
              except ImportError as e:
                  failed.append(f'{module}: {str(e)}')
          if failed:
              print('FAILED_MODULES=' + ','.join(failed))
              sys.exit(1)
          print('ALL_MODULES_OK')
          "
      register: python_module_check
      changed_when: false

    - name: Assert all critical Python modules are available
      ansible.builtin.assert:
        that:
          - python_module_check.rc == 0
          - "'ALL_MODULES_OK' in python_module_check.stdout"
        fail_msg: "Python modules missing or failed to import: {{ python_module_check.stdout }}"
        success_msg: "All critical Python modules are available"
