---
- name: Verify
  hosts: all
  gather_facts: true

  vars_files:
    - ../../defaults/main.yml

  vars:
    ansible_user: ansible
    ansible_become_password: ansible

  tasks:
    - name: Check installed version
      ansible.builtin.include_tasks: "../../tasks/noauto_check_installed_version.yml"

    - name: Assert installed version is correct
      ansible.builtin.assert:
        that:
          - "python_installed_version == python_version"

    - name: Check Python tool install directory exists
      ansible.builtin.stat:
        path: "{{ python_tool_install_path }}"
      register: python_tool_dir

    - name: Assert Python tool directory exists
      ansible.builtin.assert:
        that:
          - python_tool_dir.stat.exists
          - python_tool_dir.stat.isdir

    - name: Check PATH profile script exists
      ansible.builtin.stat:
        path: "/etc/profile.d/python_path.sh"
      register: python_path_script

    - name: Assert PATH profile script exists
      ansible.builtin.assert:
        that:
          - python_path_script.stat.exists

    - name: Check wrapper script exists
      ansible.builtin.stat:
        path: "{{ python_tool_install_path }}/frida"
      register: python_frida_wrapper

    - name: Assert frida wrapper exists and is executable
      ansible.builtin.assert:
        that:
          - python_frida_wrapper.stat.exists
          - python_frida_wrapper.stat.executable

    - name: Test frida command is accessible via PATH
      ansible.builtin.shell: |
        . /etc/profile.d/python_path.sh
        which frida
      register: python_frida_which
      changed_when: false

    - name: Assert frida is found in PATH
      ansible.builtin.assert:
        that:
          - python_frida_which.stdout is match(".*/" + python_tool_install_dir + "/frida")

    - name: Verify critical Python modules are available
      ansible.builtin.command:
        cmd: |
          python3 -c "
          import sys
          modules = ['ssl', 'sqlite3', 'zlib', 'bz2', 'lzma', 'readline', '_ctypes', '_gdbm', '_curses']
          failed = []
          for module in modules:
              try:
                  __import__(module)
              except ImportError as e:
                  failed.append(f'{module}: {str(e)}')
          if failed:
              print('FAILED_MODULES=' + ','.join(failed))
              sys.exit(1)
          print('ALL_MODULES_OK')
          "
      register: python_module_check
      changed_when: false

    - name: Assert all critical Python modules are available
      ansible.builtin.assert:
        that:
          - python_module_check.rc == 0
          - "'ALL_MODULES_OK' in python_module_check.stdout"
        fail_msg: "Python modules missing or failed to import: {{ python_module_check.stdout }}"
        success_msg: "All critical Python modules are available"
