---
- name: Verify
  hosts: all
  gather_facts: true
  vars_files:
    - ../../defaults/main.yml

  tasks:
    - name: Check installed version
      ansible.builtin.include_tasks: "../../tasks/noauto_check_installed_version.yml"

    - name: Assert installed version is correct
      ansible.builtin.assert:
        that:
          - "python_installed_version == python_version"

    - name: Check Python tool install directory exists
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.local/bin"
      register: python_tool_dir

    - name: Assert Python tool directory exists
      ansible.builtin.assert:
        that:
          - python_tool_dir.stat.exists
          - python_tool_dir.stat.isdir

    - name: Check PATH profile script exists
      ansible.builtin.stat:
        path: "/etc/profile.d/python_path.sh"
      register: python_path_script

    - name: Assert PATH profile script exists
      ansible.builtin.assert:
        that:
          - python_path_script.stat.exists

    - name: Check wrapper script exists
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.local/bin/frida"
      register: python_frida_wrapper

    - name: Assert frida wrapper exists and is executable
      ansible.builtin.assert:
        that:
          - python_frida_wrapper.stat.exists
          - python_frida_wrapper.stat.executable

    - name: Test frida command is accessible via PATH
      ansible.builtin.shell: |
        . /etc/profile.d/python_path.sh
        which frida
      register: python_frida_which
      changed_when: false

    - name: Assert frida is found in PATH
      ansible.builtin.assert:
        that:
          - python_frida_which.stdout is match(".*/.local/bin/frida")
